version: "3"

services:
  database:
    image: postgres:16.2-alpine
    container_name: lambcast_database
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  psql_data:
